include::../attributes.txt[]

// Attributes

[.topic]
[#ref-cli-cmd-context]
= `cdk context`
:keywords: {aws} CDK, {aws} CDK CLI, CDK Toolkit, IaC, Infrastructure as code, {aws} Cloud, {aws} CloudFormation, cdk context

[abstract]
--
Manage cached context values for your {aws} CDK application.
--

// Content start

Manage cached context values for your {aws} CDK application.

_Context_ represents the configuration and environment information that can influence how your stacks are synthesized and deployed. Use `cdk context` to do the following:

* View your configured context values.
* Set and manage context values.
* Remove context values.

[#ref-cli-cmd-context-usage]
== Usage

[source,none,subs="verbatim,attributes"]
----
$ cdk context <options>
----

[#ref-cli-cmd-context-options]
== Options

For a list of global options that work with all CDK  CLI commands, see  xref:ref-cli-cmd-options[Global options].


[#ref-cli-cmd-context-options-clear]
`--clear <BOOLEAN>`::
Clear all context.

[#ref-cli-cmd-context-options-force]
`--force, -f <BOOLEAN>`::
Ignore missing key error.
+
_Default value_: `false`

[#ref-cli-cmd-context-options-help]
`--help, -h <BOOLEAN>`::
Show command reference information for the `cdk context` command.

[#ref-cli-cmd-context-options-reset]
`--reset, -e <STRING>`::
The context key, or its index, to reset.