include::../attributes.txt[]

// Attributes

[.topic]
[#ref-cli-cmd-rollback]
= `cdk rollback`
:keywords: {aws} CDK, {aws} CDK CLI, CDK Toolkit, IaC, Infrastructure as code, {aws} Cloud, {aws} CloudFormation, cdk deploy, rollback

[abstract]
--
Use the {aws} Cloud Development Kit ({aws} CDK) Command Line Interface (CLI) `cdk rollback` command to rollback a failed or paused stack from an {aws} CloudFormation deployment to its last stable state.
--

// Content start

Use the {aws} Cloud Development Kit ({aws} CDK) Command Line Interface (CLI) `cdk rollback` command to rollback a failed or paused stack from an {aws} CloudFormation deployment to its last stable state.

[NOTE]
====

To use this command, you must have v23 of the bootstrap template deployed to your environment. For more information, see xref:bootstrap-template-history[Bootstrap template version history].

====

When you deploy using `cdk deploy`, the CDK CLI will rollback a failed deployment by default. If you specify  `--no-rollback` with `cdk deploy`, you can then use the `cdk rollback` command to manually rollback a failed deployment. This will initiate a rollback to the last stable state of your stack.

[#ref-cli-cmd-rollback-usage]
== Usage

[source,none,subs="verbatim,attributes"]
----
$ cdk rollback <arguments> <options>
----

[#ref-cli-cmd-rollback-args]
== Arguments

[#ref-cli-cmd-rollback-args-stack-name]
*CDK stack ID*::
The construct ID of the CDK stack from your app to rollback.
+
_Type_: String
+
_Required_: No

[#ref-cli-cmd-rollback-options]
== Options

For a list of global options that work with all CDK  CLI commands, see xref:ref-cli-cmd-options[Global options].

[#ref-cli-cmd-rollback-options-all]
`--all <BOOLEAN>`::
Rollback all stacks in your CDK app.
+
_Default value_: `false`

[#ref-cli-cmd-rollback-options-force]
`--force, -f <BOOLEAN>`::
When you use `cdk rollback`, some resources may fail to rollback. Provide this option to force the rollback of all resources. This is the same behavior as providing the `--orphan` option for each resource in your stack.
+
_Default value_: `false`

[#ref-cli-cmd-rollback-options-help]
`--help, -h <BOOLEAN>`::
Show command reference information for the `cdk rollback` command.

[#ref-cli-cmd-rollback-options-orphan]
`--orphan <LogicalId>`::
When you use `cdk rollback`, some resources may fail to rollback. When this happens, you can try to force the rollback of a resource by using this option and providing the logical ID of the resource that failed to rollback.
+
This option can be provided multiple times in a single command The following is an example:
+
[source,none,subs="verbatim,attributes"]
----
$ cdk rollback MyStack --orphan MyLambdaFunction --orphan MyLambdaFunction2
----
+
To force the rollback of all resources, use the `--force` option instead.

[#ref-cli-cmd-rollback-options-toolkit-stack-name]
`--toolkit-stack-name <STRING>`::
The name of the existing CDK Toolkit stack that the environment is bootstrapped with.
+
By default, `cdk bootstrap` deploys a stack named `CDKToolkit` into the specified {aws} environment. Use this option to provide a different name for your bootstrap stack.
+
The CDK CLI uses this value to verify your bootstrap stack version.

[#ref-cli-cmd-rollback-options-validate-bootstrap-version]
`--validate-bootstrap-version <BOOLEAN>`::
Specify whether to validate the bootstrap stack version. Provide `--validate-bootstrap-version=false` or `--no-validate-bootsrap-version` to turn off this behavior.
+
_Default value_: `true`