include::attributes.txt[]

// Attributes
[.topic]
:info_titleabbrev: Bootstrapping
:keywords: {aws} CDK, {aws} Cloud Development Kit ({aws} CDK), {aws} account, {aws} Region, Bootstrapping, Bootstrap, Environment

[#bootstrapping]
= {aws} CDK bootstrapping

[abstract]
--
_Bootstrapping_ is the process of preparing your {aws} environment for usage with the {aws} Cloud Development Kit ({aws} CDK). Before you deploy a CDK stack into an {aws} environment, the environment must first be bootstrapped.
--

// Content start

_Bootstrapping_ is the process of preparing your {aws} environment for usage with the {aws} Cloud Development Kit ({aws} CDK). Before you deploy a CDK stack into an {aws} environment, the environment must first be bootstrapped.

[#bootstrapping-what]
== What is bootstrapping?

Bootstrapping prepares your {aws} environment by provisioning specific {aws} resources in your environment that are used by the {aws} CDK. These resources are commonly referred to as your _bootstrap resources_. They include the following:

* *Amazon Simple Storage Service (Amazon S3) bucket* – Used to store your CDK project files, such as {aws} Lambda function code and assets.
* *Amazon Elastic Container Registry (Amazon ECR) repository* – Used primarily to store [.noloc]`Docker` images.
* *{aws} Identity and Access Management (IAM) roles* – Configured to grant permissions needed by the {aws} CDK to perform deployments. For more information about the IAM roles created during bootstrapping, see xref:bootstrapping-env-roles[IAM roles created during bootstrapping].

[#bootstrapping-how]
== How does bootstrapping work?

Resources and their configuration that are used by the CDK are defined in an {aws} CloudFormation template. This template is created and managed by the CDK team. For the latest version of this template, see https://github.com/aws/aws-cdk-cli/blob/main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml[`bootstrap-template.yaml`] in the _aws-cdk-cli [.noloc]`GitHub` repository_.

To bootstrap an environment, you use the {aws} CDK Command Line Interface ({aws} CDK CLI)  `cdk bootstrap` command. The CDK CLI retrieves the template and deploys it to {aws} CloudFormation as a stack, known as the _bootstrap stack_. By default, the stack name is `CDKToolkit`. By deploying this template, CloudFormation provisions the resources in your environment. After deployment, the bootstrap stack will appear in the {aws} CloudFormation console of your environment.

You can also customize bootstrapping by modifying the template or by using CDK CLI options with the `cdk bootstrap` command.

{aws} environments are independent. Each environment that you want to use with the {aws} CDK must first be bootstrapped.

[#bootstrapping-learn]
== Learn more

For instructions on bootstrapping your environment, see  xref:bootstrapping-env[Bootstrap your environment for use with the {aws} CDK].