include::attributes.txt[]

// Attributes
[.topic]
[#cli-telemetry]
= Configure {aws} CDK CLI telemetry
:info_titleabbrev: Configure CDK CLI telemetry 
:keywords: {aws} CDK CLI, reporting, usage data, telemetry

[abstract]
--
The {aws} Cloud Development Kit ({aws} CDK) collects anonymous telemetry data on CLI usage to gain insight into how the {aws} CDK CLI is being used.
--

// Content start

[#telemetry-intro]
== What is CDK CLI telemetry?

[IMPORTANT]
====
{aws} CDK CLI telemetry is only collected in {aws} CDK CLI versions 2.1100.0 and up.
====

The {aws} Cloud Development Kit ({aws} CDK) collects anonymous telemetry data on CLI usage to gain insight into how the {aws} CDK CLI is being used.

The data being collected is as follows:

[cols="1,2,4", options="header"]
|===
|Metric |Description |Reason

|CDK CLI Version
|CLI version (x.y.z)
|Collecting this will help us bisect our data by version, which can help us identify problematic versions.

|Installation ID
|Random UUID stored on local machines executing CLI commands
|This helps us estimate the distinct number of users who are either 1) affected by an error, or 2) use a specific CLI feature. Each unique machine will have their own Installation ID that is generated randomly via UUID V4.

|Session ID
|Random UUID generated on each CLI command invocation
|This helps us identify all the events originating from the same command.

|Event ID
|The Session ID plus a counter
|This creates a unique identifier for each event in a session.

|Region
|AWS Region
|This will help us bisect our data for region-specific issues.

|Timestamp
|The time (generated by the client) the data is sent to our telemetry endpoint
|This will help us generate time series graphs.

|Event State
|The "result" of the event. Possible values are 'SUCCESS', 'FAILURE', 'ABORTED'
|This will help us track error rates on each CLI command and alert us to potential regressions before they are reported by customers.

|Event Type
|An identifier for the type of event that produces the data
|Since we aim to send metrics on a per-event basis, and there could be multiple events in a command execution, this is an enum that identifies what kind of event transpired. Values could be 'synth', 'deploy', etc..

|Command Path
|The command and properties entered into the CLI, with any free text redacted
|For example, cdk deploy myStack would be turned into ['cdk', 'deploy', '$STACK1'] in the telemetry data. This information is critical to determine feature usage and will help us make data-driven decisions on what CLI features to prioritize.

|Command Parameters
|The optional parameters entered into the CLI, with any free text redacted
|Some of our features include parameters, like cdk deploy --watch. This information is critical to determine feature usage and for us to make data-driven decisions.

|Configuration
|Additional parameters that may affect the CLI command (i.e. cdk.context.json or context values in cdk.json / ~/.cdk.json), with any free text redacted
|This will help us facilitate debugging by providing a comprehensive view of all possible parameters that may affect the behavior of the CLI.

|Operating System
|The operating system that is being used
|This will help us debug issues that only affect specific operating systems.

|CI/CD
|Whether or not the CLI command is being invoked from a CI/CD environment
|Helps us prioritize CLI features that better facilitate CI/CD environments.

|Node Version
|The node version used in the environment
|This will help us debug any node-specific issues that arise.

|Timers
|The length of the event (and potentially, any smaller denominations that are interesting)
|We will monitor the duration of events like (but not limited to) synthesis, deploy, etc..

|Counters
|Various counter metrics derived from your CDK app and CLI execution
|We will monitor how counting stats like (but not limited to) CFN resource count affect the duration of deploy.

|Dependencies
|Relevant AWS dependencies and their versions
|We plan to track AWS dependencies that might affect the CLI result, like aws-cdk-lib, jsii, projen, etc..

|Error Names
|The name of the error, if an error occurs.
|We only record error names that we control.
|===

Customers are opted in to CLI usage data collection and reporting by default. You can opt out of CDK CLI telemetry using the CDK CLI, context values, an environment variable, or DNS filtering.

[#telemetry-opt-out]
== How to opt out of CDK CLI telemetry

To view your current telemetry status based on context values and environment variables, run the following command:

[source,none,subs="verbatim,attributes"]
----
cdk cli-telemetry --status
----
[#telemetry-context]
=== Opt out using context values
If there are conflicts in the context values from various sources, the CDK uses the following order of precedence.

. Context values specified using a CDK CLI command with the `--context` option
. Context values in cdk.json
. Context values in cdk.context.json
. Context values in ~/.cdk.json

*To opt out using a CDK CLI command*

Run the following CDK CLI command to disable telemetry:

[source,none,subs="verbatim,attributes"]
----
cdk cli-telemetry --disable
----

Running this command records the action to your local `cdk.context.json` file and applies to the current CDK application only.

*To opt out using the application configuration file*

Set `cli-telemetry: false` in an application's `cdk.json` file. This disables telemetry for the application.

*To opt out using the global configuration file*

Set `cli-telemetry: false` in the `~/.cdk.json` file to disable telemetry for all CDK applications on the same computer. You must specify this setting inside a context element as follows:
----
{
  "context": { 
    "cli-telemetry": false
  }
}
----

[#telemetry-environment-variable]
=== Opt out using an environment variable

Set the `CDK_DISABLE_CLI_TELEMETRY` environment variable to `true` to disable CLI telemetry in that environment. 

[source,none,subs="verbatim,attributes"]
----
CDK_DISABLE_CLI_TELEMETRY=true
----
The value of this environment variable takes precendence over any context values that have been set. 

[TIP]
====
Add this environment variable to your shell startup file, such as `.bashrc`, to disable telemetry every time you open a terminal window.
====

[#telemetry-dns]
=== Opt out using DNS filtering

The telemetry endpoint is `cdk-cli-telemetry.us-east-1.api.aws/metrics`.
Blocking this domain name in your firewall disables CLI telemetry and does not affect CDK CLI functionality.

[#telemetry-optout-all]
=== Opt out of all usage data reporting

To opt out of all usage data reporting for a single command, use the `--no-version-reporting` global CLI option. This option turns off both application usage data collection and CDK CLI telemetry. 

If you are currently opting out of application usage data collection using the `--no-version-reporting` option, you are automatically opted out of CDK CLI telemetry for that specific command execution, regardless of context values.

[NOTE]
====
If you set `analyticsReporting` at the stack level, it takes precedence over the `--no-version-reporting` option for application usage data collection only.
====

[#telemetry-data-file]
== Send telemetry data to a local file

If you choose to stay opted in to CDK CLI telemetry, you can choose to send your telemetry data to a local file. You can then review the file to audit the telemetry data we are collecting.  

Use the following option to send telemetry data to a local file:
[source,none,subs="verbatim,attributes"]
----
 --telemetry-file='path/to/local/file'
----

[NOTE]
====
The `--telemetry-file` option is being released prior to the launch of the telemetry feature. It is considered production-ready and safe to use. However, you must opt in by providing the `--unstable` option. The `--unstable` flag will be ignored after launch.
====

The following command sends telemetry data to a local file:
[source,none,subs="verbatim,attributes"]
----
cdk deploy --unstable=telemetry --telemetry-file='path/to/local/file'
----
