include::attributes.txt[]

// Attributes

[.topic]
[#configure-access]
= Configure security credentials for the {aws} CDK CLI
:info_titleabbrev: Configure security credentials
:keywords: {aws}, {aws} CDK, {aws} CDK CLI, Programmatic access, Security credentials, IAM, IAM Identity Center

[abstract]
--
When you use the {aws} Cloud Development Kit ({aws} CDK) to develop applications in your local environment, you will primarily use the {aws} CDK  CLI to interact with {aws} to deploy and manage your CDK stacks. To use the CDK  CLI, you must configure security credentials.
--

// Content start

When you use the {aws} Cloud Development Kit ({aws} CDK) to develop applications in your local environment, you will primarily use the {aws} CDK Command Line Interface ({aws} CDK  CLI) to interact with {aws}. For example, you can use the CDK  CLI to deploy your application or to delete your resources from your {aws} environment.

To use the CDK CLI to interact with {aws}, you must configure security credentials on your local machine. This lets {aws} know who you are and what permissions you have.

To learn more about security credentials, see https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds.html[{aws} security credentials] in the _IAM User Guide_.

[#configure-access-prerequisites,]
== Prerequisites

Configuring security credentials is part of the _getting started_ process. Complete all prerequisites and previous steps at xref:getting-started[Getting started with the {aws} CDK].

[#configure-access-how]
== How to configure security credentials

How you configure security credentials depends on how you or your organization manages users. Whether you use {aws} Identity and Access Management (IAM) or {aws} IAM Identity Center, we recommend that you use the {aws} Command Line Interface ({aws} CLI) to configure and manage security credentials for the CDK  CLI. This includes using {aws} CLI commands like `aws configure` to configure security credentials on your local machine. However, you can use alternative methods such as manually updating your `config` and `credentials` files, or setting environment variables.

For guidance on configuring security credentials using the {aws} CLI, along with information on configuration and credential precedence when using different methods, see https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-authentication.html[Authentication and access credentials] in the _{aws} Command Line Interface User Guide_. The CDK CLI adheres to the same configuration and credential precedence of the {aws} CLI. The  `--profile` command line option takes precedence over environment variables. If you have both the `AWS_PROFILE` and `CDK_DEFAULT_PROFILE` environment variables configured, the `AWS_PROFILE` environment variable takes precedence.

If you configure multiple profiles, you can use the CDK CLI ``xref:ref-cli-cmd-options-profile[--profile]`` option with any command to specify the profile from your `credentials` and `config` files to use for authentication. If you don't provide `--profile`, the `default` profile will be used.

If you prefer to quickly configure basic settings, including security credentials, see https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html[Set up the {aws} CLI] in the _{aws} Command Line Interface User Guide_.

Once you've configured security credentials on your local machine, you can use the CDK CLI to interact with {aws}.

[#configure-access-sso]
== Configure and manage security credentials for IAM Identity Center users

IAM Identity Center users can authenticate with IAM Identity Center or manually by using short-term credentials.

[#configure-access-sso-auto]
*Authenticate with IAM Identity Center to generate short-term credentials*::
+
You can configure the {aws} CLI to authenticate with IAM Identity Center. This is the recommended approach of configuring security credentials for IAM Identity Center users. IAM Identity Center users can use the {aws} CLI `aws configure sso` wizard to configure an IAM Identity Center profile and `sso-session`, which gets stored in the `config` file on your local machine. For instructions, see  https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html[Configure the {aws} CLI to use {aws} IAM Identity Center] in the _{aws} Command Line Interface User Guide_.
+
Next, you can use the {aws} CLI `aws sso login` command to request refreshed credentials. You can also use this command to switch profiles. For instructions, see https://docs.aws.amazon.com/cli/latest/userguide/sso-using-profile.html[Use an IAM Identity Center named profile] in the _{aws} Command Line Interface User Guide_.
+
Once authenticated, you can use the CDK CLI to interact with {aws} for the duration of your session. For an example, see xref:configure-access-sso-example-cli[Example: Authenticate with IAM Identity Center automatic token refresh for use with the {aws} CDK CLI].

[#configure-access-sso-manual]
*Manually configure short-term credentials*::
+
As an alternative to using the {aws} CLI and authenticating with IAM Identity Center, IAM Identity Center users can obtain short-term credentials from the {aws} Management Console and manually configure the  `credentials` and `config` files on their local machine. Once configured, you can use the CDK  CLI to interact with {aws} until your credentials expire. For instructions, see  https://docs.aws.amazon.com/cli/latest/userguide/cli-authentication-short-term.html[Authenticate with short-term credentials] in the _{aws} Command Line Interface User Guide_.

[#configure-access-iam]
== Configure and manage security credentials for IAM users

IAM users can use an IAM role or IAM user credentials with the CDK  CLI.

[#configure-access-iam-role]
*Use an IAM role to configure short-term credentials*::
+
IAM users can assume IAM roles to gain additional (or different) permissions. For IAM users, this is the recommended approach since it provides short-term credentials.
+
First, the IAM role and user's permission to assume the role must be configured. This is typically performed by an administrator using the {aws} Management Console or {aws} CLI. Then, the IAM user can use the {aws} CLI to assume the role and configure short-term credentials on their local machine. For instructions, see https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html[Use an IAM role in the {aws} CLI] in the _{aws} Command Line Interface User Guide_.

[#configure-access-iam-user]
*Use IAM user credentials*::
+
[WARNING]
====

To avoid security risks, we don't recommend using IAM user credentials since they provide long-term access. If you must use long-term credentials, we recommend that you link:https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#rotate-credentials[update access keys] as an IAM security best practice.

====
+
IAM users can obtain access keys from the {aws} Management Console. You can then use the {aws} CLI to configure long-term credentials on your local machine. For instructions, see  https://docs.aws.amazon.com/cli/latest/userguide/cli-authentication-user.html[Authenticate with IAM user credentials] in the _{aws} Command Line Interface User Guide_.

[#configure-access-info,]
== Additional information

To learn about the different ways that you can sign in to {aws}, depending on the type of user you are, see  https://docs.aws.amazon.com/signin/latest/userguide/what-is-sign-in.html[What is {aws} Sign-In?] in the _{aws} Sign-In User Guide_.

For reference information when using {aws} SDKs and tools, including the {aws} CLI, see the  https://docs.aws.amazon.com/sdkref/latest/guide/overview.html[{aws} SDKs and Tools Reference Guide].

include::configure-access-sso-example-cli.adoc[leveloffset=+1]