include::attributes.txt[]

// Attributes
:https---docs-aws-amazon-com-general-latest-gr-rande-html-regional-endpoints: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
:https---aws-amazon-com-about-aws-global-infrastructure-regions-az-: https://aws.amazon.com/about-aws/global-infrastructure/regions_az/

[.topic]
:info_titleabbrev: Environments
:keywords: {aws} CDK, {aws} Cloud Development Kit ({aws} CDK), environment, env, {aws} account, {aws} Region

[#environments]
= Environments for the {aws} CDK

[abstract]
--
An environment consists of the {aws} account and {aws} Region that you deploy an {aws} Cloud Development Kit ({aws} CDK) stack to.
--

// Content start

An environment consists of the {aws} account and {aws} Region that you deploy an {aws} Cloud Development Kit ({aws} CDK) stack to.

*{aws} account*::
When you create an {aws} account, you receive an account ID. This ID is a 12-digit number, such as **012345678901**, that uniquely identifies your account. To learn more, see https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-identifiers.html[View {aws} account identifiers] in the _{aws} Account Management Reference Guide_.

*{aws} Region*::
{aws} Regions are named by using a combination of geographical location and a number that represents an Availability Zone in the Region. For example, *[.noloc]`us-east-1`* represents an Availability Zone in the US East (N. Virginia) Region. To learn more about {aws} Regions, see https://aws.amazon.com/about-aws/global-infrastructure/regions_az/[Regions and Availability Zones]. For a list of Region codes, see https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints[Regional endpoints] in the _{aws} General Reference_ Reference Guide.

The {aws} CDK can determine environments from your credentials and configuration files. These files can be created and managed with the {aws} Command Line Interface ({aws} CLI). The following is a basic example of these files:

*Credentials file*::
+
[source,toml,subs="verbatim,attributes"]
----
[default]
aws_access_key_id=ASIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
aws_session_token = IQoJb3JpZ2luX2IQoJb3JpZ2luX2IQoJb3JpZ2luX2IQoJb3JpZ2luX2IQoJb3JpZVERYLONGSTRINGEXAMPLE

[user1]
aws_access_key_id=ASIAI44QH8DHBEXAMPLE
aws_secret_access_key=je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY
aws_session_token = fcZib3JpZ2luX2IQoJb3JpZ2luX2IQoJb3JpZ2luX2IQoJb3JpZ2luX2IQoJb3JpZVERYLONGSTRINGEXAMPLE
----

*Configuration file*::
+
[source,toml,subs="verbatim,attributes"]
----
[default]
region=us-west-2
output=json

[profile user1]
region=us-east-1
output=text
----

You can pass environment information from these files in your CDK code through environment variables that are provided by the CDK. When you run a CDK  CLI command, such as `cdk deploy`, you then provide the profile from your credentials and configuration files to gather environment information from.

The following is an example of specifying these environment variables in your CDK code:

[source,javascript,subs="verbatim,attributes"]
----
new MyDevStack(app, 'dev', {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION
}});
----

The following is an example of passing values associated with the  `user1` profile from your credentials and configuration files to the CDK CLI using the  `--profile` option. Values from these files will be passed to your environment variables:

[source,bash,subs="verbatim,attributes"]
----
$ cdk deploy <myStack> --profile <user1>
----

Instead of using values from the credentials and configuration files, you can also hard-code environment values in your CDK code. The following is an example:

[source,javascript,subs="verbatim,attributes"]
----
const envEU = { account: '238383838383', region: 'eu-west-1' };
const envUSA = { account: '837873873873', region: 'us-west-2' };

new MyFirstStack(app, 'first-stack-us', { env: envUSA });
new MyFirstStack(app, 'first-stack-eu', { env: envEU });
----

[#environments-learn]
== Learn more

To get started with using environments with the {aws} CDK, see  xref:configure-env[Configure environments to use with the {aws} CDK].