include::attributes.txt[]

// Attributes
[.topic]
[#node-versions]
= Supported Node.js versions for the {aws} CDK
:info_titleabbrev: Supported Node versions
:keywords: {aws} CDK, {aws} Cloud Development Kit ({aws} CDK), node versions, supported versions, aws-cdk-cli, aws-cdk-lib, end of life, EOL, deprecation

[abstract]
--
The {aws} Cloud Development Kit ({aws} CDK) runs on Node.js. This includes the {aws} CDK CLI (`aws-cdk-cli`), {aws} Construct Library (`aws-cdk-lib`), as well as broader ecosystem tools such as [.noloc]`JSII`, [.noloc]`Projen`, and [.noloc]`CDK8s`. This page documents the Node.js runtime versions compatible with the {aws} CDK, helping you maintain a supported development environment.
--

// Content start

The {aws} Cloud Development Kit ({aws} CDK) runs on Node.js. This includes the {aws} CDK CLI (`aws-cdk-cli`), {aws} Construct Library (`aws-cdk-lib`), as well as broader ecosystem tools such as [.noloc]`JSII`, [.noloc]`Projen`, and [.noloc]`CDK8s`.

[#node-version-support-policy]
== Version support policy

The {aws} CDK supports Node.js Long Term Support (LTS) versions. When a Node.js version reaches its community End-of-Life (EOL), the {aws} CDK continues to support it for an additional 6 months before ending support.

After support ends, the {aws} CDK team will no longer provide security patches, bug fixes, or compatibility updates for that Node.js version. Using the {aws} CDK with an unsupported Node.js version may result in unexpected behavior, errors, or security vulnerabilities.

For upcoming Node.js release and EOL dates, see the link:https://github.com/nodejs/Release#release-schedule[Node.js release schedule].

[#node-version-supported]
== Supported Node.js versions

The following table lists Node.js versions currently supported by the {aws} CDK.

[cols="1,1,1", options="header"]
|===
|Node.js version
|Node.js EOL date
|CDK support end date

|24.x
|2028-04-30
|2028-10-30

|22.x
|2027-04-30
|2027-10-30

|20.x
|2026-04-30
|2026-10-30
|===

[#node-version-deprecated]
== Node.js versions no longer supported

The following Node.js versions are no longer supported by the {aws} CDK.

[cols="1,1,1", options="header"]
|===
|Node.js version
|Node.js EOL date
|CDK support ended

|18.x
|2025-05-30
|2025-11-30

|16.x
|2023-09-11
|2025-05-30

|14.x
|2023-04-30
|2025-05-30
|===
