include::attributes.txt[]

// Attributes
[.topic]
[#prerequisites]
= {aws} CDK prerequisites
:info_titleabbrev: Prerequisites
:keywords: {aws} CDK, Prerequisites, {aws} account, IAM, IAM Identity Center

[abstract]
--
Complete prerequisites before getting started with the {aws} Cloud Development Kit ({aws} CDK).
--

// Content start

Complete all prerequisites before getting started with the {aws} Cloud Development Kit ({aws} CDK).

[[sign-up-for-aws,sign-up-for-aws.title]]
== Sign up for an {aws} account

To get started with {aws}, you need an {aws} account. For information about creating an {aws} account, see https://docs.aws.amazon.com/accounts/latest/reference/getting-started.html[Getting started with an {aws} account] in the __{aws} Account Management Reference Guide__.

[#prerequisites-cli]
== Install and configure the {aws} CLI

When you develop {aws} CDK applications on your local machine, you will use the {aws} Cloud Development Kit ({aws} CDK) Command Line Interface (CLI) to interact with {aws}, such as deploying applications to provision your {aws} resources. To interact with {aws} outside of the {aws} Management Console, you must configure security credentials on your local machine. To do this, we recommend that you install and use the {aws} Command Line Interface ({aws} CLI).

For instructions on installing the {aws} CLI, see https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Install or update to the latest version of the {aws} CLI] in the _{aws} Command Line Interface User Guide_.

How you configure security credentials will depend on how you or your organization manages users. For instructions, see https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-authentication.html[Authentication and access credentials] in the _{aws} Command Line Interface User Guide_.

After installing and configuring the {aws} CLI, you should have the following:

* The {aws} CLI installed on your local machine.
* Credentials configured in a `config` on your local machine using the {aws} CLI.

[#prerequisites-node]
== Install [.noloc]`Node.js` and programming language prerequisites

All {aws} CDK developers, regardless of the supported programming language that you will use, require https://nodejs.org/en/download/[Node.js] 22.x or later. All supported programming languages use the same backend, which runs on [.noloc]`Node.js`. We recommend a version in link:https://nodejs.org/en/about/releases/[active long-term support]. 

For more information on supported Node.js versions, see xref:node-versions[Supported Node versions].

Other programming language prerequisites depend on the language that you will use to develop {aws} CDK applications:

====
[role="tablist"]
TypeScript::
* TypeScript 3.8 or later (`npm -g install typescript`)

JavaScript::
* No additional requirements

Python::
* Python 3.9 or later including `pip` and `virtualenv`

Java::
* Java Development Kit (JDK) 8 (a.k.a. 1.8) or later
* Apache Maven 3.5 or later
+
Java IDE recommended (we use [.noloc]`Eclipse`` in some examples in this guide). IDE must be able to import Maven projects. Check to make sure that your project is set to use Java 1.8. Set the JAVA_HOME environment variable to the path where you have installed the JDK.

C#::
.NET 8.0 or later.
+
Visual Studio 2019 (any edition) or Visual Studio Code recommended.

Go::
Go 1.23 or later.

====

[NOTE]
.Third-party language deprecation
====

Each language version is only supported until it is [.noloc]`EOL` (End Of Life) and is subject to change with prior notice.

====

[#prerequisites-next]
== Next steps

To get started with the {aws} CDK, see xref:getting-started[Getting started with the {aws} CDK].