include::attributes.txt[]

// Attributes

[.topic]
[#ref-cli-cmd-ack]
= `cdk acknowledge`
:info_titleabbrev: cdk ack
:keywords: {aws} CDK, {aws} CDK CLI, CDK Toolkit, IaC, Infrastructure as code, {aws} Cloud, {aws} CloudFormation, cdk acknowledge, cdk ack

[abstract]
--
Acknowledge a notice by issue number and hide it from displaying again.
--

// Content start

Acknowledge a notice by issue number and hide it from displaying again.

This is useful to hide notices that have been addressed or do not apply to you.

Acknowledgements are saved at a CDK project level. If you acknowledge a notice in one CDK project, it will still display in other projects until acknowledged there.

[#ref-cli-cmd-ack-usage]
== Usage

[source,none,subs="verbatim,attributes"]
----
$ cdk acknowledge <arguments> <options>
----

[#ref-cli-cmd-ack-args]
== Arguments

[#ref-cli-cmd-ack-args-notice-id]
*Notice ID*::
The ID of the notice.
+
_Type_: String
+
_Required_: No

[#ref-cli-cmd-ack-options]
== Options

For a list of global options that work with all CDK CLI commands, see  xref:ref-cli-cmd-options[Global options].

[#ref-cli-cmd-ack-options-help]
`--help, -h <BOOLEAN>`::
Show command reference information for the `cdk acknowledge` command.

[#ref-cli-cmd-ack-examples]
== Examples

[#ref-cli-cmd-ack-examples-1]
=== Acknowledge and hide a notice that displays when running another CDK CLI command

[source,none,subs="verbatim,attributes"]
----
$ cdk deploy
... # Normal output of the command

NOTICES

16603   Toggling off auto_delete_objects for Bucket empties the bucket

        Overview: If a stack is deployed with an S3 bucket with
                  auto_delete_objects=True, and then re-deployed with
                  auto_delete_objects=False, all the objects in the bucket
                  will be deleted.
                  
        Affected versions: <1.126.0.
        
        More information at: https://github.com/aws/aws-cdk/issues/16603
        
        
17061   Error when building EKS cluster with monocdk import

        Overview: When using monocdk/aws-eks to build a stack containing
                  an EKS cluster, error is thrown about missing
                  lambda-layer-node-proxy-agent/layer/package.json.
                  
        Affected versions: >=1.126.0 <=1.130.0.
        
        More information at: https://github.com/aws/aws-cdk/issues/17061
        
$ cdk acknowledge 16603
----