include::attributes.txt[]

// Attributes

[.topic]
[#ref-cli-cmd-publish-assets]
= `cdk publish-assets`
:keywords: {aws} CDK, {aws} CDK CLI, CDK Toolkit, IaC, Infrastructure as code, {aws} Cloud, {aws} CloudFormation, cdk publish-assets, assets, Amazon ECR, Amazon S3

[abstract]
--
Publish assets for the specified {aws} CDK stack to their respective destinations without performing a deployment.
--

// Content start

[IMPORTANT]
====
The `cdk publish-assets` command is in development for the {aws} CDK. The current features of this command are subject to change. Therefore, you must opt in by providing the `--unstable=publish-assets` option to use this command.
====

Publish assets such as Docker images and file assets for the specified {aws} Cloud Development Kit ({aws} CDK) stack to their respective destinations, such as Amazon Elastic Container Registry (Amazon ECR) repositories and Amazon Simple Storage Service (Amazon S3) buckets, without performing a deployment.

This command is useful in CI/CD pipelines where you want to separate the asset publishing phase from the deployment phase. By publishing assets independently, you can validate that all assets are built and available before you start the deployment process.

[#ref-cli-cmd-publish-assets-usage]
== Usage

[source,none,subs="verbatim,attributes"]
----
$ cdk publish-assets <arguments> <options>
----

[#ref-cli-cmd-publish-assets-args]
== Arguments

[#ref-cli-cmd-publish-assets-args-stack-name]
*CDK stack ID*::
The construct ID of the CDK stack from your app to publish assets for.
+
_Type_: String
+
_Required_: No

[#ref-cli-cmd-publish-assets-options]
== Options

For a list of global options that work with all CDK CLI commands, see xref:ref-cli-cmd-options[Global options].

[#ref-cli-cmd-publish-assets-options-all]
`--all <BOOLEAN>`::
Publish assets for all stacks in your CDK app.
+
_Default value_: `false`

[#ref-cli-cmd-publish-assets-options-concurrency]
`--concurrency <NUMBER>`::
Specify the maximum number of simultaneous asset publishing operations to perform.
+
_Default value_: `4`

[#ref-cli-cmd-publish-assets-options-exclusively]
`--exclusively, -e <BOOLEAN>`::
Only publish assets for requested stacks and don't include dependencies.

[#ref-cli-cmd-publish-assets-options-force]
`--force <BOOLEAN>`::
Re-publish all assets, even if they already exist at the destination.
+
_Default value_: `false`

[#ref-cli-cmd-publish-assets-options-help]
`--help, -h <BOOLEAN>`::
Show command reference information for the `cdk publish-assets` command.

[#ref-cli-cmd-publish-assets-examples]
== Examples

[#ref-cli-cmd-publish-assets-examples-1]
=== Publish assets for a specific stack

[source,none,subs="verbatim,attributes"]
----
$ cdk publish-assets MyStack --unstable=publish-assets
----

[#ref-cli-cmd-publish-assets-examples-2]
=== Publish assets for all stacks

[source,none,subs="verbatim,attributes"]
----
$ cdk publish-assets --all --unstable=publish-assets
----

[#ref-cli-cmd-publish-assets-examples-3]
=== Force re-publish assets that already exist

[source,none,subs="verbatim,attributes"]
----
$ cdk publish-assets MyStack --unstable=publish-assets --force
----

[#ref-cli-cmd-publish-assets-examples-4]
=== Publish assets then deploy separately

First, publish assets for your stack:

[source,none,subs="verbatim,attributes"]
----
$ cdk publish-assets MyStack --unstable=publish-assets
----

Then, deploy the stack:

[source,none,subs="verbatim,attributes"]
----
$ cdk deploy MyStack
----