include::attributes.txt[]

// Attributes

[.topic]
[#ref-cli-cmd-list]
= `cdk list`
:keywords: {aws} CDK, {aws} CDK CLI, CDK Toolkit, IaC, Infrastructure as code, {aws} Cloud, {aws} CloudFormation, cdk list

[abstract]
--
List all {aws} CDK stacks and their dependencies from a CDK app.
--

// Content start

List all {aws} CDK stacks and their dependencies from a CDK app.

[#ref-cli-cmd-list-usage]
== Usage

[source,none,subs="verbatim,attributes"]
----
$ cdk list <arguments> <options>
----

[#ref-cli-cmd-list-args]
== Arguments

[#ref-cli-cmd-list-args-stack-name]
*CDK stack ID*::
The construct ID of the CDK stack from your app to perform this command against.
+
_Type_: String
+
_Required_: No

[#ref-cli-cmd-list-options]
== Options

For a list of global options that work with all CDK  CLI commands, see xref:ref-cli-cmd-options[Global options].

[#ref-cli-cmd-list-options-help]
`--help, -h <BOOLEAN>`::
Show command reference information for the `cdk list` command.

[#ref-cli-cmd-list-options-long]
`--long, -l <BOOLEAN>`::
Display {aws} environment information for each stack.
+
_Default value_: `false`

[#ref-cli-cmd-list-options-show-dependencies]
`--show-dependencies, -d <BOOLEAN>`::
Display stack dependency information for each stack.
+
_Default value_: `false`

[#ref-cli-cmd-list-examples]
== Examples

[#ref-cli-cmd-list-examples-1]
=== List all stacks in the CDK app '`node bin/main.js`'

[source,none,subs="verbatim,attributes"]
----
$ cdk list --app='node bin/main.js'
Foo
Bar
Baz
----

[#ref-cli-cmd-list-examples-]
=== List all stacks, including {aws} environment details for each stack

[source,none,subs="verbatim,attributes"]
----
$ cdk list --app='node bin/main.js' --long
-
    name: Foo
    environment:
        name: 000000000000/bermuda-triangle-1
        account: '000000000000'
        region: bermuda-triangle-1
-
    name: Bar
    environment:
        name: 111111111111/bermuda-triangle-2
        account: '111111111111'
        region: bermuda-triangle-2
-
    name: Baz
    environment:
        name: 333333333333/bermuda-triangle-3
        account: '333333333333'
        region: bermuda-triangle-3
----