include::attributes.txt[]

// Attributes

[.topic]
[#ref-cli-cmd-diff]
= `cdk diff`
:keywords: {aws} CDK, {aws} CDK CLI, CDK Toolkit, IaC, Infrastructure as code, {aws} Cloud, {aws} CloudFormation, cdk diff

[abstract]
--
Perform a diff to see infrastructure changes between {aws} CDK stacks.
--

// Content start

Perform a diff to see infrastructure changes between {aws} CDK stacks.

This command is typically used to compare differences between the current state of stacks in your local CDK app against deployed stacks. However, you can also compare a deployed stack with any local {aws} CloudFormation template.

[#ref-cli-cmd-diff-usage]
== Usage

[source,none,subs="verbatim,attributes"]
----
$ cdk diff <arguments> <options>
----

[#ref-cli-cmd-diff-args]
== Arguments

[#ref-cli-cmd-diff-args-stack-name]
*CDK stack ID*::
The construct ID of the CDK stack from your app to perform a diff.
+
_Type_: String
+
_Required_: No

[#ref-cli-cmd-diff-options]
== Options

For a list of global options that work with all CDK  CLI commands, see  xref:ref-cli-cmd-options[Global options].


[#ref-cli-cmd-diff-options-change-set]
`--change-set <BOOLEAN>`::
Specify whether to create a change set to analyze resource replacements.
+
When `true`, the CDK CLI will create an {aws} CloudFormation change set to display the exact changes that will be made to your stack. This output includes whether resources will be updated or replaced. The CDK  CLI uses the deploy role instead of the lookup role to perform this action.
+
When `false`, a quicker, but less-accurate diff is performed by comparing CloudFormation templates. Any change detected to properties that require resource replacement will be displayed as a resource replacement, even if the change is purely cosmetic, like replacing a resource reference with a hard-coded ARN.
+
_Default value_: `true`

[#ref-cli-cmd-diff-options-context-lines]
`--context-lines <NUMBER>`::
Number of context lines to include in arbitrary JSON diff rendering.
+
_Default value_: `3`

[#ref-cli-cmd-diff-options-exclusively]
`--exclusively, -e <BOOLEAN>`::
Only diff requested stacks and don't include dependencies.

[#ref-cli-cmd-diff-options-fail]
`--fail <BOOLEAN>`::
Fail and exit with a code of `1` if differences are detected.

[#ref-cli-cmd-diff-options-help]
`--help, -h <BOOLEAN>`::
Show command reference information for the `cdk diff` command.

[#ref-cli-cmd-diff-options-processed]
`--processed <BOOLEAN>`::
Specify whether to compare against the template with CloudFormation transforms already processed.
+
_Default value_: `false`

[#ref-cli-cmd-diff-options-quiet]
`--quiet, -q <BOOLEAN>`::
Do not print the CDK stack name and default `cdk diff` message to `stdout` when no changes are detected.
+
_Default value_: `false`

[#ref-cli-cmd-diff-options-security-only]
`--security-only <BOOLEAN>`::
Only diff for broadened security changes.
+
_Default value_: `false`

[#ref-cli-cmd-diff-options-strict]
`--strict <BOOLEAN>`::
Modify `cdk diff` behavior to be more precise or stringent. When true, the CDK CLI will not filter out `{aws}::CDK::Metadata` resources or unreadable non-ASCII characters.
+
_Default value_: `false`

[#ref-cli-cmd-diff-options-template]
`--template <STRING>`::
The path to the CloudFormation template to compare a CDK stack with.

[#ref-cli-cmd-diff-examples]
== Examples

[#ref-cli-cmd-diff-examples-1]
=== Diff against the currently deployed stack named MyStackName

The CDK  CLI uses the following symbols in the diff output:

* `[+]` – Identifies code or resources that will be added if you deploy your changes.
* `[-]` – Identifies code or resources that will be removed if you deploy your changes.
* `[~]` – Identifies a resource or property that will be modified if you deploy your changes.

The following is an example that shows a diff of local changes to a Lambda function:

[source,none,subs="verbatim,attributes"]
----
$ cdk diff MyStackName
start: Building <asset-hash>:<account:Region>
success: Built <asset-hash>:<account:Region>
start: Publishing <asset-hash>:<account:Region>
success: Published <asset-hash>:<account:Region>
Hold on while we create a read-only change set to get a diff with accurate replacement information (use --no-change-set to use a less accurate but faster template-only diff)
Stack MyStackName
Resources
[~] {aws}::Lambda::Function HelloWorldFunction <resource-logical-ID>
 └─ [~] Code
     └─ [~] .ZipFile:
         ├─ [-] 
        exports.handler = async function(event) {
          return {
            statusCode: 200,
            body: JSON.stringify('Hello World!'),
          };
        };
      
         └─ [+] 
        exports.handler = async function(event) {
          return {
            statusCode: 200,
            body: JSON.stringify('Hello from CDK!'),
          };
        };
      


✨  Number of stacks with differences: 1
----

A  `[~]` indicator for resources that will be modified does not always mean a full resource replacement:

* Some resource properties, like `Code`, will update the resource.
* Some resource properties, like `FunctionName`, may cause a full resource replacement.

[#ref-cli-cmd-diff-examples-2]
=== Diff against a specific CloudFormation template

[source,none,subs="verbatim,attributes"]
----
$ cdk diff MyStackName --app='node bin/main.js' --template-path='./MyStackNameTemplate.yaml'
----

[#ref-cli-cmd-diff-examples-3]
=== Diff a local stack with its deployed stack. don't print to stdout if no changes are detected

[source,none,subs="verbatim,attributes"]
----
$ cdk diff MyStackName --app='node bin/main.js' --quiet
----