include::attributes.txt[]

// Attributes
[.topic]
[#security]
= Security for the {aws} Cloud Development Kit ({aws} CDK)
:info_titleabbrev: Security

[abstract]
--
Provides security-related information for the {aws} CDK.
--

// Content start

Cloud security at Amazon Web Services ({aws}) is the highest priority. As an {aws} customer, you benefit from a data center and network architecture that is built to meet the requirements of the most security-sensitive organizations. Security is a shared responsibility between {aws} and you. The link:https://aws.amazon.com/compliance/shared-responsibility-model/[Shared Responsibility Model] describes this as Security of the Cloud and Security in the Cloud.

*Security of the Cloud* – {aws} is responsible for protecting the infrastructure that runs all of the services offered in the {aws} Cloud and providing you with services that you can use securely. Our security responsibility is the highest priority at {aws}, and the effectiveness of our security is regularly tested and verified by third-party auditors as part of the https://aws.amazon.com/compliance/programs/[{aws} Compliance Programs].

*Security in the Cloud* – Your responsibility is determined by the {aws} service you are using, and other factors including the sensitivity of your data, your organization's requirements, and applicable laws and regulations.

The {aws} CDK follows the link:https://aws.amazon.com/compliance/shared-responsibility-model/[shared responsibility model] through the specific Amazon Web Services ({aws}) services it supports. For {aws} service security information, see the link:https://docs.aws.amazon.com/security/?id=docs_gateway#aws-security[{aws} service security documentation page] and https://aws.amazon.com/compliance/services-in-scope/[{aws} services that are in scope of {aws} compliance efforts by compliance program].

include::security-iam.adoc[leveloffset=+1]


include::compliance-validation.adoc[leveloffset=+1]


include::disaster-recovery-resiliency.adoc[leveloffset=+1]


include::infrastructure-security.adoc[leveloffset=+1]