include::attributes.txt[]

// Attributes
[.topic]
[#toolkit-library]
= Perform programmatic actions using the CDK Toolkit Library
:info_titleabbrev: Use the CDK Toolkit Library
:keywords: CDK Toolkit Library, Programmatic access, {aws} CDK, {aws} Cloud Development Kit ({aws} CDK), deploy, {aws} CloudFormation, Infrastructure as Code, synthesize

[abstract]
--
The {aws} Cloud Development Kit ({aws} CDK) Toolkit Library enables you to perform {aws} CDK actions requiring programmatic access on {aws}.
--

// Content start

[NOTE]
====

CDK Toolkit Library is in developer preview and is subject to change.

====

[#toolkit-library-intro]
== What is the CDK Toolkit Library Library?

The {aws} Cloud Development Kit ({aws} CDK) Toolkit Library enables you to perform {aws} CDK actions requiring programmatic access on {aws}. You can use the CDK Toolkit Library to implement actions such as bootstrapping, synthesizing, and deploying through code rather than CDK  CLI commands. With this library, you can create custom tools, build specialized  CLI applications, and integrate CDK programmatic access capabilities into your development workflows.

The following is an example, that installs the CDK Toolkit Library and uses it to deploy a cloud assembly of your CDK app:

[source,javascript,subs="verbatim,attributes"]
----
import { Toolkit } from '@aws-cdk/toolkit-lib'; // Install the CDK Toolkit Library

const cdk = new Toolkit(); // Create a CDK Toolkit instance

// ...

// Implement a deployment
await cdk.deploy(cloudAssembly, { 
   deploymentMethod: { method: "direct" }, // Configure deployment options
   ...
})
----

[#toolkit-library-gs]
== Get started with the CDK Toolkit Library
To get started, see the `link:https://www.npmjs.com/package/@aws-cdk/toolkit-lib[ReadMe]` in the _@aws-cdk/toolkit-lib_ `npm` package.

For API reference information, see the link:https://docs.aws.amazon.com/cdk/api/toolkit-lib/[CDK Toolkit Library API reference].